javascript:document.write( '<script type=\"text/javascript\">\n' );
document.write( '                window.jstiming.load.tick(\'scl\');\n' );
document.write( '              </script>\n' );
document.write( '<div id=\"sites-chrome-main-wrapper-inside\">\n' );
document.write( '<table id=\"sites-chrome-main\" class=\"sites-layout-hbox\" cellspacing=\"0\" cellpadding=\"{scmCellpadding}\" border=\"0\">\n' );
document.write( '<tr>\n' );
document.write( '<td id=\"sites-chrome-sidebar-left\" class=\"sites-layout-sidebar-left initial\" style=\"width:200px\">\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" id=\"COMP_2bd\" class=\"sites-embed\" role=\"navigation\"><div class=\"sites-embed-content sites-sidebar-nav\"><ul role=\"navigation\" jotId=\"navList\" class=\"has-expander\"><li class=\"topLevel nav-first \"></div></li></ul></div></div>\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" id=\"COMP_7064869330994039\" class=\"sites-sidebar-plusone-wrapper\"><div class=\"g-plusone\" data-count=\"true\" data-size=\"standard\" data-source=\"google:sites\"></div></div>\n' );
document.write( '</td>\n' );
document.write( '<td id=\"sites-canvas-wrapper\">\n' );
document.write( '<div id=\"sites-canvas\" role=\"main\">\n' );
document.write( '<div id=\"goog-ws-editor-toolbar-container\"> </div>\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" id=\"title-crumbs\" style=\"display: none;\">\n' );
document.write( '<A href=\"/site/unblockedgamesix/action-games\" dir=\"ltr\">Action Games</A>‎ > ‎\n' );
document.write( '  </div>\n' );
document.write( '<h3 xmlns=\"http://www.w3.org/1999/xhtml\" id=\"sites-page-title-header\" style=\"display: none;\" align=\"left\">\n' );
document.write( '<span id=\"sites-page-title\" dir=\"ltr\" tabindex=\"-1\" style=\"outline: none\">Slope</span>\n' );
document.write( '</h3>\n' );
document.write( '<div id=\"sites-canvas-main\" class=\"sites-canvas-main\">\n' );
document.write( '<div id=\"sites-canvas-main-content\">\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sites-layout-name-one-column-hf sites-layout-vbox\"><div class=\"sites-layout-tile sites-tile-name-header\"><div dir=\"ltr\"><div class=\"sites-embed-align-center-wrapping-off\"><div class=\"sites-embed-border-off sites-embed\" style=\"width:800px;\"><div class=\"sites-embed-content sites-embed-type-ggs-gadget\"><iframe title=\"Include gadget (iframe)\" width=\"800\" height=\"640\" scrolling=\"no\" frameborder=\"0\" id=\"78970250\" name=\"78970250\" allowtransparency=\"true\" class=\"igm\" src=\"//mj89sp3sau2k7lj1eg3k40hkeppguj6j-a-sites-opensocial.googleusercontent.com/gadgets/ifr?url=http://www.gstatic.com/sites-gadgets/iframe/iframe.xml&container=enterprise&view=default&lang=en&country=ALL&sanitize=0&v=28632ca282af2706&libs=core&mid=36&parent=https://sites.google.com/site/unblockedgamesix/action-games/slope#up_scroll=no&up_iframeURL=https://tmm-slope.surge.sh&st=e%3DAIHE3cAe9Yszy3Nktaif1cEok1l7%252FFT8Vt09ameTcPB4b0BV5pfQEsShIR5vBypygEQCOS4K5cIaQ73vyjNLS0qSaJ65WiqkZFIOyISlgAbhHymcARvOa1R1KvZQA1o7LnU9vrlEHIrD%26c%3Denterprise&rpctoken=-6679199808403297607\"></iframe></div></div></div></div></div><div class=\"sites-layout-tile sites-tile-name-content-1\"><div dir=\"ltr\"><h1><a name=\"TOC-Slope-Unblocked\">\n' );
document.write( '</div> \n' );
document.write( '</div> \n' );
document.write( '<div id=\"sites-canvas-bottom-panel\">\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" id=\"COMP_page-subpages\"> </div>\n' );
document.write( '<div id=\"sites-attachments-container\">\n' );
document.write( '</div>\n' );
document.write( '<a xmlns=\"http://www.w3.org/1999/xhtml\" name=\"page-comments\"></a>\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" id=\"COMP_page-comments\"><div class=\"sites-comment-docos-wrapper\"><div class=\"sites-comment-docos\"><div class=\"sites-comment-docos-background\"></div><div class=\"sites-comment-docos-header\"></div><div id=\"sites-comment-docos-pane\" class=\"sites-comment-docos-pane\"></div></div></div></div>\n' );
document.write( '</div>\n' );
document.write( '</div> \n' );
document.write( '</td> \n' );
document.write( '</tr>\n' );
document.write( '</table> \n' );
document.write( '</div> \n' );
document.write( '</div> \n' );
document.write( '<div id=\"sites-chrome-footer-wrapper\">\n' );
document.write( '<div id=\"sites-chrome-footer-wrapper-inside\">\n' );
document.write( '<div id=\"sites-chrome-footer\">\n' );
document.write( '<div xmlns=\"http://www.w3.org/1999/xhtml\" class=\"sites-subfooter\"><div class=\"sites-subfooter-content\"><br /></div></div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div>\n' );
document.write( '</div> \n' );
document.write( '</div> \n' );
document.write( '<div id=\"sites-chrome-adminfooter-container\">\n' );
document.write( '\n' );
document.write( '</div>\n' );
document.write( '</div> \n' );
document.write( '</div> \n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '    window.jstiming.load.tick(\'sjl\');\n' );
document.write( '  </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" src=\"https://ssl.gstatic.com/sites/p/20c50a/system/js/jot_min_view__en.js\"></script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '    window.jstiming.load.tick(\'jl\');\n' );
document.write( '  </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '                    sites.Searchbox.initialize(\n' );
document.write( '                        \'sites-searchbox-search-button\',\n' );
document.write( '                        {\"object\":[]}[\'object\'],\n' );
document.write( '                        \'search-site\',\n' );
document.write( '                        {\"label\":\"Configure search options...\",\"url\":\"/site/unblockedgamesix/system/app/pages/admin/settings\"});\n' );
document.write( '                  </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '      gsites.HoverPopupMenu.createSiteDropdownMenus(\'sites-header-nav-dropdown\', false);\n' );
document.write( '    </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\" defer=\"true\">\n' );
document.write( '            JOT_setupNav(\"2bd\", \"Điều hướng\", true);\n' );
document.write( '            JOT_addListener(\'titleChange\', \'JOT_NAVIGATION_titleChange\', \'COMP_2bd\');\n' );
document.write( '          </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '              new sites.CommentPane(\'//docs.google.com/comments/u/0/d/AAHRpnXvxeV4dz17kJ3ooY5tJ_dhOOUudtjFa9niT_w2BX2x5ofLq5W_Afmc2fozg-vN06hTKdxH1rCv1OO7kyhARcHHmCxyZWtO59h4hQ1GXPkBavf5HhYNdGRot_-1lG9fbqk9Gh6yh/api/js?token=AGNctVaDwEFUWyXP_bJHKBVbxKySK939lQ:1600730076058\',\n' );
document.write( '                  false, false);\n' );
document.write( '            </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\">\n' );
document.write( '                    window.onload = function() {\n' );
document.write( '                      if (false) {\n' );
document.write( '                        JOT_setMobilePreview();\n' );
document.write( '                      }\n' );
document.write( '                      var loadTimer = window.jstiming.load;\n' );
document.write( '                      loadTimer.tick(\"ol\");\n' );
document.write( '                      loadTimer[\"name\"] = \"load,\" + webspace.page.type + \",user_page\";\n' );
document.write( '                      window.jstiming.report(loadTimer, {}, \'https://gg.google.com/csi\');\n' );
document.write( '                    }\n' );
document.write( '                  </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '        JOT_insertAnalyticsCode(false,\n' );
document.write( '            false);\n' );
document.write( '      </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '    var maestroRunner = new gsites.pages.view.SitesMaestroRunner(\n' );
document.write( '        webspace, \"en\");\n' );
document.write( '    maestroRunner.initListeners();\n' );
document.write( '    maestroRunner.installEditRender();\n' );
document.write( '  </script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\" defer=\"true\">\n' );
document.write( '  //<![CDATA[\n' );
document.write( '    // Decorate any fastUI buttons on the page with a class of \'goog-button\'.\n' );
document.write( '    if (webspace.user.hasWriteAccess) {\n' );
document.write( '      JOT_decorateButtons();\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    // Fires delayed events.\n' );
document.write( '    (function() {\n' );
document.write( '      JOT_fullyLoaded = true;\n' );
document.write( '      var delayedEvents = JOT_delayedEvents;\n' );
document.write( '      for (var x = 0; x < delayedEvents.length; x++) {\n' );
document.write( '        var event = delayedEvents[x];\n' );
document.write( '        JOT_postEvent(event.eventName, event.eventSrc, event.payload);\n' );
document.write( '      }\n' );
document.write( '      JOT_delayedEvents = null;\n' );
document.write( '      JOT_postEvent(\'pageLoaded\');\n' );
document.write( '    })();\n' );
document.write( '  //]]>\n' );
document.write( '</script>\n' );
document.write( '<script xmlns=\"http://www.w3.org/1999/xhtml\" type=\"text/javascript\">\n' );
document.write( '    JOT_postEvent(\'decorateGvizCharts\');\n' );
document.write( '  </script>\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( '          JOT_setupPostRenderingManager();\n' );
document.write( '        </script>\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( '          JOT_postEvent(\'renderPlus\', null, \'sites-chrome-main\');\n' );
document.write( '        </script>\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( '          sites.codeembed.init();\n' );
document.write( '        </script>\n' );
document.write( '<div id=\"server-timer-div\" style=\"display:none\"> </div>\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( '          window.jstiming.load.tick(\'render\');\n' );
document.write( '          JOT_postEvent(\'usercontentrendered\', this);\n' );
document.write( '        </script>\n' );
document.write( '</body>\n' );
document.write( '</html>\n' );
